ALTER TABLE users ADD COLUMN delete_info JSONB DEFAULT NULL;
ALTER TABLE rides ADD COLUMN delete_info JSONB DEFAULT NULL;
ALTER TABLE driver_locations ADD COLUMN delete_info JSONB DEFAULT NULL;
ALTER TABLE payments ADD COLUMN delete_info JSONB DEFAULT NULL;
