server:
  port: 9000
  servlet:
    context-path: /v1

spring:
  application:
    name: core-api

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  datasource:
    url: jdbc:postgresql://localhost:5432/ridehailingdb
    username: ridehailing_api
    password: ridehailing123
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  jackson:
    deserialization:
      fail-on-unknown-properties: true
    serialization:
      write-dates-as-timestamps: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.ridehailing.core_api.config
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  newrelic:
    metrics:
      export:
        enabled: true
        api-key: ${NEW_RELIC_API_KEY:}
        account-id: ${NEW_RELIC_ACCOUNT_ID:}
        step: 30s

jwt:
  secret: randomstringrandomstringrandomstringrandomstringrandomstringrandomstring
  expiration-ms: 86400000

logging:
  level:
    com.ridehailing: DEBUG
